name: opendata

services:
  juritcom-api:
    build:
      target: api-local
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/node
    extra_hosts:
      - "host.docker.internal:host-gateway"
